export const LOGIN_NURSE_REQUEST = "LOGIN_NURSE_REQUEST";
export const LOGIN_NURSE_ERROR = "LOGIN_NURSE_ERROR";
export const LOGIN_NURSE_SUCCESS = "LOGIN_NURSE_SUCCESS";

export const LOGIN_DOCTOR_SUCCESS = "LOGIN_DOCTOR_SUCCESS";
export const LOGIN_DOCTOR_ERROR = "LOGIN_DOCTOR_ERROR";
export const LOGIN_DOCTOR_REQUEST = "LOGIN_DOCTOR_REQUEST";

export const LOGIN_ADMIN_ERROR = "LOGIN_ADMIN_ERROR";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REGISTER_DOCTOR_SUCCESS = " REGISTER_DOCTOR_SUCCESS";
export const REGISTER_DOCTOR_ERROR = "REGISTER_DOCTOR_ERROR";
export const REGISTER_DOCTOR_REQUEST = "REGISTER_DOCTOR_REQUEST";

export const REGISTER_NURSE_SUCCESS = " REGISTER_NURSE_SUCCESS";
export const REGISTER_NURSE_ERROR = "REGISTER_NURSE_ERROR";
export const REGISTER_NURSE_REQUEST = "REGISTER_NURSE_REQUEST";

export const REGISTER_ADMIN_SUCCESS = " REGISTER_ADMIN_SUCCESS";
export const REGISTER_ADMIN_ERROR = "REGISTER_ADMIN_ERROR";
export const REGISTER_ADMIN_REQUEST = "REGISTER_ADMIN_REQUEST";

export const REGISTER_AMBULANCE_SUCCESS = " REGISTER_AMBULANCE_SUCCESS";
export const REGISTER_AMBULANCE_ERROR = "REGISTER_AMBULANCE_ERROR";
export const REGISTER_AMBULANCE_REQUEST = "REGISTER_AMBULANCE_REQUEST";
