export const CREATE_REPORT_SUCCESS = " CREATE_REPORT_SUCCESS";
export const CREATE_REPORT_ERROR = "CREATE_REPORT_ERROR";
export const CREATE_REPORT_REQUEST = "CREATE_REPORT_REQUEST";

export const GET_DOCTOR_SUCCESS = " GET_DOCTOR_SUCCESS";
export const GET_DOCTOR_ERROR = "GET_DOCTOR_ERROR";
export const GET_DOCTOR_REQUEST = "GET_DOCTOR_REQUEST";

export const GET_APPOINTMENT_SUCCESS = " GET_APPOINTMENT_SUCCESS";
export const GET_APPOINTMENT_ERROR = "GET_APPOINTMENT_ERROR";
export const GET_APPOINTMENT_REQUEST = "GET_APPOINTMENT_REQUEST";

export const ADD_PATIENT_SUCCESS = " ADD_PATIENT_SUCCESS";
export const ADD_PATIENT_ERROR = "ADD_PATIENT_ERROR";
export const ADD_PATIENT_REQUEST = "ADD_PATIENT_REQUEST";

export const ADD_BED_SUCCESS = " ADD_BED_SUCCESS";
export const ADD_BED_ERROR = "ADD_BED_ERROR";
export const ADD_BED_REQUEST = "ADD_BED_REQUEST";

export const GET_BED_SUCCESS = " GET_BED_SUCCESS";
export const GET_BED_ERROR = "GET_BED_ERROR";
export const GET_BED_REQUEST = "GET_BED_REQUEST";

export const CREATE_BOOKING_SUCCESS = " CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_ERROR = "CREATE_BOOKING_ERROR";
export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
